# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_jarrett AD32FE57D2833DBF457C9AB1979C631C96E72E85
  - &host_nixos age1e0td9nmh795pl2ptlpyhqsas9de406pgs4hglrje5kc070dt9c3q70u2wu
  - &host_nixos_framework age1placeholder_replace_with_actual_key_later
creation_rules:
  - path_regex: secrets/host_nixos/.*
    pgp: *admin_jarrett
    age: *host_nixos
  - path_regex: secrets/host_nixos_framework/.*
    pgp: *admin_jarrett
    age: *host_nixos_framework
